[project]
name = "mcp-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "anthropic>=0.52.2",
    "fastmcp>=2.6.1",
    "openai>=1.95.1",
    "prompt-toolkit>=3.0.51",
    "requests>=2.32.3",
]
